language: r
sudo: false
cache: packages
r_packages:
  - covr
before_script:
  - Rscript -e 'vaultr::vault_test_server_install()'
  - R CMD INSTALL .
after_success:
  - Rscript -e 'covr::codecov()'
r_github_packages:
  - ropensci/cyphr
  - vimc/montagu-r
  - vimc/vaultr
env:
  global:
    - VAULTR_TEST_SERVER_INSTALL=true
    - VAULTR_TEST_SERVER_PORT=18200
    - VAULT_BIN_PATH=$PWD/.vault
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      - libsodium-dev
      - libssl-dev
