# This file must contain keys 'source' and 'destination'; each of
# those must contain a field 'driver' that will be one of
# RSQLite::SQLite or RPostgres::Postgres (other drives may work too).
#
# For example, a configuration to use Postgres as the *source*
# database might look like:
#
#   source:
#     driver: RPostgres::Postgres
#     host: localhost
#     port: 5432
#     username: myuser
#     database: databasename
#     password: p4ssw0rd
#
# All arguments other than driver are optional and will be passed
# through during the 'DBI::dbConnect()' call.
#
# A configuration that uses SQLite for the destination database might
# look like
#
#   destination:
#     driver: RSQLite::SQLite
#     dbname: reports.sqlite
#
# The "dbname" argument will be interpreted relative to the orderly
# root.  Be sure to exclude this path using .gitignore
#
# Other options accepted by RSQLite are allowed but are much less
# commonly useful (as of RSQLite v1.1-2, loadable.extensions,
# cache_size, synchronous, flags, vfs)

source:
  driver: ~

destination:
  driver: ~
