on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      
      
name: test

jobs:
  test:
    runs-on: ubuntu-20.04

    name: testing
    
    strategy:
      fail-fast: false
      
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        if: ${{ github.event_name == 'push' }}
        with:
          owner: vimc
          repo: workflow-test
          ref: main
          github_token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          client_payload: '{"orderly_version": "master"}'
          workflow_file_name: trigger-me.yaml
          
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        if: ${{ github.head_ref != 'master' }}
        with:
          owner: vimc
          repo: workflow-test
          ref: main
          github_token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          client_payload: '{"orderly_version": "${{ github.head_ref }}"}'
          workflow_file_name: trigger-me.yaml
